create extension if not exists pgcrypto;

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  answers jsonb not null default '{}'::jsonb,
  contact jsonb not null default '{}'::jsonb,
  result jsonb,
  completed boolean not null default false,
  discovery_requested boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id) on delete set null,
  type text not null check (type in ('screen_view', 'click')),
  screen text check (
    screen is null
    or screen in ('hero', 's1', 'fact1', 's2', 'fact2', 's3', 's4', 's5', 's6', 's7', 's8', 'result', 'admin')
  ),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.discovery_requests (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id) on delete set null,
  company_name text not null,
  name text not null,
  wa text not null check (length(regexp_replace(wa, '\D', '', 'g')) between 9 and 16),
  budget_context text,
  message text,
  created_at timestamptz not null default now()
);

create index if not exists events_session_id_idx on public.events(session_id);
create index if not exists events_screen_type_idx on public.events(screen, type);
create index if not exists events_created_at_idx on public.events(created_at desc);
create index if not exists sessions_completed_idx on public.sessions(completed);
create index if not exists sessions_discovery_requested_idx on public.sessions(discovery_requested);
create index if not exists sessions_created_at_idx on public.sessions(created_at desc);
create index if not exists sessions_updated_at_idx on public.sessions(updated_at desc);
create index if not exists discovery_requests_session_id_idx on public.discovery_requests(session_id);
create index if not exists discovery_requests_created_at_idx on public.discovery_requests(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sessions_set_updated_at on public.sessions;
create trigger sessions_set_updated_at
before update on public.sessions
for each row
execute function public.set_updated_at();

alter table public.sessions enable row level security;
alter table public.events enable row level security;
alter table public.discovery_requests enable row level security;

-- The app writes through SUPABASE_SERVICE_ROLE_KEY from server-side API routes.
-- No anon/authenticated policies are created intentionally, so public browser clients cannot read these tables directly.
