alter table if exists public.discovery_requests
  add column if not exists employee_count text,
  add column if not exists yearly_revenue text;

create table if not exists public.prompt_learning_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id) on delete set null,
  source_type text not null check (source_type in ('session_result', 'discovery_request')),
  source_ref text not null,
  recommendation jsonb not null default '{}'::jsonb,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists prompt_learning_events_session_id_idx on public.prompt_learning_events(session_id);
create index if not exists prompt_learning_events_created_at_idx on public.prompt_learning_events(created_at desc);

alter table if exists public.prompt_learning_events enable row level security;
